import { Category, Product } from './types';

export const CATEGORIES: Category[] = [
  {
    id: 'tech',
    name: 'Elettronica & Tech',
    slug: 'tech',
    description: 'Gadget imperdibili e accessori smart.'
  },
  {
    id: 'home',
    name: 'Casa & Cucina',
    slug: 'home',
    description: 'Tutto il necessario per una casa moderna.'
  },
  {
    id: 'fashion',
    name: 'Moda & Accessori',
    slug: 'fashion',
    description: 'Stile e comfort per ogni occasione.'
  },
  {
    id: 'sports',
    name: 'Sport & Tempo Libero',
    slug: 'sports',
    description: 'Attrezzatura per il tuo benessere.'
  }
];

// ELENCO MANUALE DEI PRODOTTI
// Copia e incolla gli oggetti qui sotto per aggiungere nuovi prodotti.
// Assicurati che l'ID sia univoco per ogni prodotto.

export const ALL_PRODUCTS: Product[] = [
  // --- CATEGORIA TECH ---
  {
    id: 'tech-1',
    categoryId: 'tech',
    title: 'Apple iPhone 17',
    description: 'Apple iPhone 17 256 GB: display 6,3" con ProMotion, chip A19, fotocamera frontale Center Stage per selfie di gruppo più facili, più resistenza ai graffi, un giorno intero di batteria; Nero',
    price: 979.00,
    rating: 4.6,
    reviewCount: 186,
    // Nota: Usa l'URL dell'immagine reale di Amazon (tasto destro sull'immagine > copia indirizzo immagine)
    imageUrl: 'https://m.media-amazon.com/images/I/61X5FknDWuL._AC_SX522_.jpg', 
    affiliateLink: 'https://amzn.to/4qhletc', // <-- INSERISCI QUI IL TUO LINK
    isPrime: true,
    isBestSeller: true,
  },
  {
    id: 'tech-2',
    categoryId: 'tech',
    title: 'Samsung Galaxy Book3 360',
    description: 'Samsung Galaxy Book3 360 Laptop, 3 anni di garanzia, 13.3" Super AMOLED, S Pen, Intel Core i5, 8GB RAM, 256GB SSD, Windows 11 Home, Graphite',
    price: 749.00,
    rating: 4.3,
    reviewCount: 20,
    imageUrl: 'https://m.media-amazon.com/images/I/71P2Ef9JTDL._AC_SX679_.jpg',
    affiliateLink: 'https://amzn.to/455jKd0',
    isPrime: true,
    isBestSeller: false,
  },
  {
    id: 'tech-3',
    categoryId: 'tech',
    title: 'Cover Compatibile con Nothing Phone 3a Pro',
    description: 'Cover Compatibile con Nothing Phone 3a Pro, Protezione Completa,Telaio Rigido in PC + TPU, Anticaduta, Custodia Compatibile con Nothing Phone 3a Pro.(Grigio Trasparente)',
    price: 8.99,
    rating: 3.0,
    reviewCount: 1,
    imageUrl: 'https://m.media-amazon.com/images/I/61WUKedVreL._AC_SL1500_.jpg',
    affiliateLink: 'https://amzn.to/4aSJQ6Q',
    isPrime: false,
    isBestSeller: false,
  },
  {
    id: 'tech-4',
    categoryId: 'tech',
    title: 'Motorola moto g56 5G 8/256GB',
    description: 'Motorola moto g56 5G 8/256GB, Fotocamera 50MP + sensore antisfarfallio, Display 6.72" FHD+ 120Hz, batteria 5200mAh, MediaTek Dimensity 7060, Android 15, PANTONE Dill',
    price: 147.90,
	  originalPrice: 269.00,
    rating: 4.5,
    reviewCount: 322,
    imageUrl: 'https://m.media-amazon.com/images/I/51lVBJ8WJRL._AC_SX679_.jpg',
    affiliateLink: 'https://amzn.to/49vcoke',
    isPrime: true,
    isBestSeller: false,
  },

  // --- CATEGORIA CASA ---
  {
    id: 'home-1',
    categoryId: 'home',
    title: 'Klighten Applique da Parete Interno LED',
    description: 'Klighten Applique da Parete Interno LED, 24W, 1960LM, Lampada Decorative Mordern, per Camera da Letto, Soggiorno, Corridoio, 110-240V, Bianco Neutro 4000K, Bianco.',
    price: 54.99,
    rating: 4.5,
    reviewCount: 520,
    imageUrl: 'https://m.media-amazon.com/images/I/51ow0ZYT-AL._AC_SX679_.jpg',
    affiliateLink: 'https://amzn.to/49c5At4',
    isPrime: true,
    isBestSeller: true,
  },
  {
    id: 'home-2',
    categoryId: 'home',
    title: 'Moulinex Easy Fry & Grill XXL',
    description: 'Moulinex Easy Fry & Grill XXL Friggitrice ad Aria, 6,5Litri/2Kg, 2 Pietanze in 1, Cottura ad Aria e Griglia, Capacità fino a 8 Persone,1830W, 8 Programmi, App Ricette, EZ8018',
    price: 89.99,
    originalPrice: 109.99,
    rating: 4.6,
    reviewCount: 2815,
    imageUrl: 'https://m.media-amazon.com/images/I/61xBMoQF+UL._AC_SX679_.jpg',
    affiliateLink: 'https://amzn.to/4sCVZDo',
    isPrime: true,
    isBestSeller: false,
  },
  {
    id: 'home-3',
    categoryId: 'home',
    title: 'Filtri, Sostituzione per Brita Maxtra+ Plus',
    description: 'Filtri, Sostituzione per Brita Maxtra+ Plus, Maxtra Pro All-in-1 Filtro, Filtro per Bollitore Compatibile Con Brita Mavea Filtri per acqua, Riducono Cloro,Odori (12, Classic)',
    price: 29.99,
    rating: 4.2,
    reviewCount: 1586,
    imageUrl: 'https://m.media-amazon.com/images/I/714g6zAtSuL._AC_SX679_.jpg',
    affiliateLink: 'https://amzn.to/4aSlTfY',
    isPrime: true,
    isBestSeller: false,
  },
  {
    id: 'home-4',
    categoryId: 'home',
    title: 'Amazon Echo Show 11',
    description: 'Amazon Echo Show 11 (ultimo modello) - Schermo Full HD da 11" con colori vibranti, area di visione più ampia, audio spaziale e Alexa, Grafite',
    price: 211.99,
	  originalPrice: 239.99,
    rating: 4.0,
    reviewCount: 632,
    imageUrl: 'https://m.media-amazon.com/images/I/61rPQD2+EEL._AC_SY741_.jpg',
    affiliateLink: 'https://amzn.to/49uYUVI',
    isPrime: true,
    isBestSeller: true,
  },
  {
    id: 'home-5',
    categoryId: 'home',
    title: 'Curlsmith Curl Quenching',
    description: 'Curlsmith Curl Quenching Conditioning Wash - Co-wash detergente, co-wash senza solfati, per tutti i tipi di ricci, vegano e cruelty free (32 oz)',
    price: 53.00,
	  rating: 4.5,
    reviewCount: 304,
    imageUrl: 'https://m.media-amazon.com/images/I/61s317TT5eL._AC_SX522_.jpg',
    affiliateLink: 'https://amzn.to/3YCi72R',
    isPrime: true,
    isBestSeller: false,
  },
  {
    id: 'home-6',
    categoryId: 'home',
    title: 'Set di 6 bustine da tè riutilizzabili in tessuto',
    description: 'Earthtopia CoffeeCloth - Set di 6 bustine da tè riutilizzabili in tessuto, 100% cotone biologico, filtro da tè, filtro permanente, filtro riutilizzabile (5 piccoli, 1 grande).',
    price: 12.95,
    rating: 4.4,
    reviewCount: 59,
    imageUrl: 'https://m.media-amazon.com/images/I/616QweUHlaL._AC_SL1000_.jpg',
    affiliateLink: 'https://amzn.to/3YAAfdl',
    isPrime: false,
    isBestSeller: false,
  },

  // --- CATEGORIA FASHION ---
  {
    id: 'fashion-1',
    categoryId: 'fashion',
    title: 'Coppola in Tweed Irlandese',
    description: 'Borges & Scott Lo Sloan - Coppola in Tweed Irlandese e Pelle Nubuck',
    price: 74.95, 
    originalPrice: 79.95,
    rating: 4.3,
    reviewCount: 103,
    imageUrl: 'https://m.media-amazon.com/images/I/81OrR6D76zL._AC_SX679_.jpg',
    affiliateLink: 'https://amzn.to/4syR5Hd',
    isPrime: true,
    isBestSeller: false,
  },
  {
    id: 'fashion-2',
    categoryId: 'fashion',
    title: 'Maserati Traguardo Orologio Uomo',
    description: 'Maserati Traguardo Orologio Uomo LIMITED EDITION, al quarzo, Cronografo - R8873612052',
    price: 167.85, 
    originalPrice: 208.23,
    rating: 4.6,
    reviewCount: 161,
    imageUrl: 'https://m.media-amazon.com/images/I/61vfrSx5awL._AC_SX522_.jpg',
    affiliateLink: 'https://amzn.to/4pp9K5v',
    isPrime: true,
    isBestSeller: false,
  },
  {
    id: 'fashion-3',
    categoryId: 'fashion',
    title: 'BOBO BIRD Orologio da uomo al quarzo in legno',
    description: 'BOBO BIRD Orologio da uomo al quarzo in legno di sandalo rosso in acciaio inossidabile con funzione classica orologio da polso cronografo lancette luminose giorno e notte data display',
    price: 112.64,
    rating: 4.6,
    reviewCount: 148,
    imageUrl: 'https://m.media-amazon.com/images/I/71EJbGOuCuL._AC_SX679_.jpg',
    affiliateLink: 'https://amzn.to/3LaxBIm',
    isPrime: false,
    isBestSeller: false,
  },
  {
    id: 'fashion-4',
    categoryId: 'fashion',
    title: 'GeGekoko Cardigan da Donna con Cappuccio',
    description: 'GeGekoko Cardigan da Donna con Cappuccio, Manica Lunga, Cardigan in Maglia Grossa, Aperto sul Davanti, Maglione Casual Autunnale e Invernale con Tasche',
    price: 48.98,
    rating: 4.2,
    reviewCount: 893,
    imageUrl: 'https://m.media-amazon.com/images/I/61v6XIYinJL._AC_SY606_.jpg',
    affiliateLink: 'https://amzn.to/4aSKPnt',
    isPrime: false,
    isBestSeller: false,
  },

  // --- CATEGORIA SPORT ---
  {
    id: 'sports-1',
    categoryId: 'sports',
    title: 'Amazfit Balance Smartwatch 46 mm',
    description: 'Amazfit Balance Smartwatch 46 mm, Pagamento NFC, AI Fitness Coach, Batteria di 14 Giorni, Monitoraggio del Sonno e della Salute, GPS, 150 Modalità Sportive, Chiamate Bluetooth per Android e iPhone',
    price: 147.99, 
    originalPrice: 209.90,
    rating: 4.3,
    reviewCount: 4295,
    imageUrl: 'https://m.media-amazon.com/images/I/61hgX22-lQL._AC_SX522_.jpg',
    affiliateLink: 'https://amzn.to/4jxJLYd',
    isPrime: true,
    isBestSeller: false,
  },
  {
    id: 'sports-2',
    categoryId: 'sports',
    title: 'K-Sport: Torre di fitness all\' aperto',
    description: 'K-Sport: Torre di fitness all\' aperto con barra per trazioni e stazione dip, resistente alle intemperie, portata massima 150 kg, acciaio verniciato a polvere, rosso',
    price: 222.22, 
    rating: 3.9,
    reviewCount: 63,
    imageUrl: 'https://m.media-amazon.com/images/I/81t4FHH2WoL._AC_SX679_.jpg',
    affiliateLink: 'https://amzn.to/3NalUSx',
    isPrime: true,
    isBestSeller: false,
  },
  {
    id: 'sports-3',
    categoryId: 'sports',
    title: 'BLUEGORILLA Magnesite liquida',
    description: 'BLUEGORILLA Magnesite liquida, Liquid Chalk Crossfit Ultra Secco! 250ML .Migliora la Tua Presa! Magnesite Arrampicata, Sollevamento Pesi, Padel, Palestra,Ginnastica Artistica.',
    price: 16.99,
    rating: 4.4,
    reviewCount: 94,
    imageUrl: 'https://m.media-amazon.com/images/I/617D5aaXeLL._AC_SL1200_.jpg',
    affiliateLink: 'https://amzn.to/4qOC4zC',
    isPrime: false,
    isBestSeller: false,
  },
  {
    id: 'sports-4',
    categoryId: 'sports',
    title: 'Merrell Speed Remix GTX',
    description: 'Merrell Speed Remix GTX, Scarpe da Passeggio Uomo',
    price: 130.04,
    rating: 4.5,
    reviewCount: 160,
    imageUrl: 'https://m.media-amazon.com/images/I/61cW4qE4r7L._AC_SY575_.jpg',
    affiliateLink: 'https://amzn.to/49yYVrR',
    isPrime: true,
    isBestSeller: false,
  },
];
